version: 2.1
orbs:
  ship: auth0/ship@0.2.0
jobs:
  build-and-test:
    docker:
      - image: circleci/node:10
    environment:
      LANG: en_US.UTF-8
    steps:
      - checkout
      - run:
          name: Update Yarn
          command: 'sudo npm update -g yarn'
      - restore-cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save-cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Check
          command: yarn check
      - run:
          name: Tests
          command: yarn test:ci
      - run:
          name: Generate Coverage
          command: yarn test:coverage
workflows:
  build-test-report:
    jobs:
      - build-and-test
      - ship/node-publish:
          pkg-manager: yarn
          requires:
            - build-and-test
          context:
            - publish-npm
            - publish-gh
          filters:
            branches:
              only:
                - master
